language: objective-c
osx_image: xcode7.2
before_install: true
install: true
script:
  - script/cibuild Aquifer Aquifer-iOS
  - xcodebuild test -scheme Aquifer-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
  - xcodebuild build -scheme Aquifer-watchOS -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm'
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
